# -*- coding: utf-8 -*-
"""Object Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEbLTMRf1ty0A9Pj2XM43DgQMQjmdPtC
"""

import torch
from matplotlib import pyplot as plt
import cv2

model=torch.hub.load('ultralytics/yolov5','yolov5s',pretrained=True)

img_path='/download.jpg'
results=model(img_path)

results.print()

results.show()

results.save()
